#!/bin/bash
set -e

# Create Keycloak database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${KEYCLOAK_DB_USER} WITH ENCRYPTED PASSWORD '${KEYCLOAK_DB_PASSWORD}';
    CREATE DATABASE ${KEYCLOAK_DB_USER}_db OWNER ${KEYCLOAK_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${KEYCLOAK_DB_USER}_db TO ${KEYCLOAK_DB_USER};
EOSQL
